### ISSUE TITLE
[BUG]  #160 버그들

### ISSUE THREAD

**Issue by f0rever0** [Team-PocaLink/Pocalink-Client#160]
## 🌴 작업 브랜치 

fix/#160

## ✅ TODO 및 진행현황 

- [x] 내정보 수정페이지 GNB 현재 GNB 컬러 들어오기
- [x] my/sell, my/buy 정보 없을때 페이지
- [x] 배송지 최초등록시 필수 요소 없으면 제출버튼 활성화 안되게
- [x] 내정보 수정 시 전화번호 regex

## 🚧 BUG 리포트
