### ISSUE TITLE
[FEATURE] #51 Feature 구매 제시하기 페이지 잔여 UI 작업

### ISSUE THREAD

**Issue by NamjunKim12** [Team-PocaLink/Pocalink-Client#51]
## 🌴 작업 브랜치 

`feature/#이슈번호`

## 💼 TASK 개요 

- 공통 컴포넌트 개발하느라 진행이 멈췄던 구매 제시 페이지를 UI 로직을 붙여 완성합니다. 

## ✅ TODO 및 진행현황 

- [ ] 구매 제시하기 페이지 정적 UI 완성
- [ ] 해당 페이지 UI 로직 분기처리
- [ ] 서버 로직 구성 감안하여 리팩토링하기
