### ISSUE TITLE
[FEATURE] #86 제시 수락, 거절하기 페이지 GUI 개발

### ISSUE THREAD

**Issue by NamjunKim12** [Team-PocaLink/Pocalink-Client#86]
## 🌴 작업 브랜치 

`feature/#이슈번호`

## 💼 TASK 개요 

- 제시 수락하기 페이지의 입력창 폼을 디자인하고, 서버 연결 전에 미리 연결할 데이터 양식을 세팅합니다. 

## ✅ TODO 및 진행현황 

- [ ] 제시 수락하기 페이지 정적 UI 퍼블리싱 
- [ ] 인풋창 예외처리
- [ ] 입력 리코일 전역 데이터와 연동
- [ ] (가능하다면) 서버와 데이터 연동
- [ ] 페이지 라우팅
